### ISSUE TITLE
导出 data.txt 文件的内容格式如果为 Json，可能更方便后续解析

### ISSUE THREAD

**Issue by SuCicada** [Ikaros-521/voistock_voice_get#2]
追加：导出音频文件如果以`id`作为命名，可能更方便后续解析

**Comment by Ikaros-521** [comment]
有空可以加一个，把原始数据都down下来

**Comment by SuCicada** [comment]
好的，因为我今天就打算爬取数据，正好搜到有现成的，就不用我重写了。
今天应该会优化一些提上来，你可以看哪些是需要的。

**Comment by Ikaros-521** [comment]
> 

www 随便提，本来这个就没啥功能，当时只是随便搓一个弄点数据就没动了

**Comment by SuCicada** [comment]
ok，交给我吧

**Comment by Ikaros-521** [comment]
![A4B2476DD2E034F6B9E0AB9E21001E32](https://user-images.githubusercontent.com/40910637/217707614-6bda9ae8-5902-40dd-b4a2-30b2dc008d19.gif)

**Comment by SuCicada** [comment]
大佬请问有交流群之类的吗，因为我看到你有很多`nonebot`相关的仓库。

**Comment by Ikaros-521** [comment]
> 大佬请问有交流群之类的吗，因为我看到你有很多`nonebot`相关的仓库。

q群 587663288

**Comment by SuCicada** [comment]
非常感谢

**Comment by SuCicada** [comment]
问题已修复：https://github.com/Ikaros-521/voistock_voice_get/pull/3
