### ISSUE TITLE
下载会某些Page被中断，Console报错

### ISSUE THREAD

**Issue by little-wheat** [Ikaros-521/voistock_voice_get#6]
Access to XMLHttpRequest at 'https://www.voistock.com/ja/voicelist/vlist-ajax.php' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
当关键词为空，并且起始坐标=12900时，就会报这个错

**Comment by Ikaros-521** [comment]
跨域请求被淦0.0
关键词空 爬全站感觉吃不消。

**Comment by Ikaros-521** [comment]
> Access to XMLHttpRequest at 'https://www.voistock.com/ja/voicelist/vlist-ajax.php' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 当关键词为空，并且起始坐标=12900时，就会报这个错

之前搞忘了，今天确认了一下，是官方的问题，12900往后的页面资源全部500，服务器没有正常响应，还是针对性下比较好。另外全站爬现在web版的实现方式会对浏览器内存比较吃紧，爬取过后的数据都还存在全局变量中，太多会爆。
