### ISSUE TITLE
导出信息

### ISSUE THREAD

**Issue by KAMIENDER** [Ikaros-521/voistock_voice_get#7]
导出检索出的信息为空数组

**Comment by Ikaros-521** [comment]
> 导出检索出的信息为空数组

可以提供检索的内容和具体配置吗，我这测了下，可以导出数据

**Comment by KAMIENDER** [comment]
![image](https://github.com/Ikaros-521/voistock_voice_get/assets/30643514/6f36df84-ec86-484a-9854-59ef303a153b)
没有特别配置什么

**Comment by Ikaros-521** [comment]
恩，应该是数据格式有出入，我看看

**Comment by KAMIENDER** [comment]
我看接口返回，好像是json的格式有问题，我这解析也不出来

**Comment by Ikaros-521** [comment]
恩，多半是接口返回错误，把数据搞异常了

**Comment by Ikaros-521** [comment]
已修复

**Comment by Ikaros-521** [comment]
pages服务还得等一段时间才会更新

**Comment by Ikaros-521** [comment]
github pages已同步，睡觉睡觉
